### PR TITLE
Upgrade to Quarkus 2.0.0.CR3

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
We'd very much appreciate a quarkus-qpid-jms release based on Quarkus 2.0.0.CR3 to be able to test with Camel Quarkus and even on Quarkus Platform. Is there any hope for it?

**Comment by gemmellr** [comment]
Sorry, I didnt see your PR before I pushed a change of my own I had sitting waiting from earlier, I only noticed it when checking the CI results.

I had no plans to publish a release based on the CR. I don't normally, and I haven't come across anything to make me think it is particularly needed this time even despite the Quarkus version bump. The extension is very basic, hasn't changed for 2.x besides dropping Java 8 support from the build, and has worked fine with the 2.x platform build thus far I believe (albeit they haven't updated to CR3 yet, only CR2). It doesnt seem like a platform build based on the CR is expected, which would be the main reason I would see need.

**Comment by ppalaga** [comment]
Camel Quarkus currently has 300+ extensions, each of which has n dependencies. This makes the likehood of dependency incompatibilities with other Quarkus platform participants quite high for us. Being able to test early may save us some stress later. 

> It doesnt seem like a platform build based on the CR is expected

Doing a CR Platform release is perhaps a good idea. WDYT @aloubyansky?

**Comment by aloubyansky** [comment]
@ppalaga you should be able to enforce the version of Quarkus (BOM) on the dependencies that you test. You probably already do. Do you really need the Qpid extension release with a specific Quarkus version?

**Comment by gemmellr** [comment]
Sure...but again the extension itself hasnt changed, and Camel will I think already depend on everything it does, thus overriding its dependencies anyway.

**Comment by ppalaga** [comment]
Yep, you are right, I have checked what set of dependencies the qpid extension actually brings and indeed it looks quite safe. Sorry for the noise and thanks for insisting on your position :) I spontaneously tend to suspect other extension providers of being like Camel Quarkus where the dependency set is immense and there is no upgrade certainty without testing. Sorry again for my false assumptions, this is really not the case here.

**Comment by gemmellr** [comment]
No worries :)

**Comment by gemmellr** [comment]
@ppalaga just FYI that a Quarkus Qpid JMS 0.25.0 release against Quarkus 2.0.0.Final is now available on Central.

**Comment by ppalaga** [comment]
Thanks, we are testing with it already.

**Pull request closed without merging**
